#!/bin/bash

echo "=========================================="
echo "  WCAG AI PLATFORM - DAY ONE LAUNCH"
echo "=========================================="
echo ""

echo "✅ STEP 1: Email Setup"
echo "-------------------------------------------"
echo "1. Go to: https://accounts.google.com/signup"
echo "2. Create professional email (suggested names):"
echo "   - wcagcompliance.ai@gmail.com"
echo "   - accessibility.audit@gmail.com"
echo "   - wcag.solutions@gmail.com"
echo ""
echo "3. Set up signature (copy from email-setup-guide.md)"
echo "4. Install Chrome extensions:"
echo "   - Mailtrack: https://mailtrack.io"
echo "   - Streak CRM: https://www.streak.com"
echo ""
read -p "Press ENTER when email is set up..."

echo ""
echo "✅ STEP 2: Create Target List"
echo "-------------------------------------------"
echo "1. Go to: https://sheets.google.com"
echo "2. Create new spreadsheet: 'WCAG AI Prospects'"
echo "3. Add columns:"
echo "   Company | Industry | Website | Contact | Email | Violations | Score | Status"
echo ""
echo "4. Add first 20 targets from industry-target-lists.md:"
echo "   - 7 Fintech companies"
echo "   - 7 Healthcare companies"  
echo "   - 6 Debt collectors"
echo ""
read -p "Press ENTER when spreadsheet is ready..."

echo ""
echo "✅ STEP 3: Scan First 20 Companies"
echo "-------------------------------------------"
echo "For each company:"
echo "1. Visit their website/login page"
echo "2. Go to: https://wave.webaim.org/"
echo "3. Paste URL and scan"
echo "4. Take screenshot of violations"
echo "5. Count total violations"
echo "6. Add to spreadsheet"
echo ""
echo "Tools for finding login/portal pages:"
echo "  - Google: [Company] + 'login' or 'patient portal'"
echo "  - Check footer links for 'Portal' or 'Sign In'"
echo ""
read -p "Press ENTER when scans are complete..."

echo ""
echo "✅ STEP 4: Find Decision Makers"
echo "-------------------------------------------"
echo "For each company, find on LinkedIn:"
echo "  - CTO or VP Engineering (Fintech)"
echo "  - Chief Medical Information Officer (Healthcare)"
echo "  - VP Operations or Compliance Officer (Debt Collectors)"
echo ""
echo "Tools for finding emails:"
echo "  - hunter.io (50 free searches/month)"
echo "  - RocketReach (5 free lookups/month)"
echo "  - Format guess: firstname.lastname@company.com"
echo ""
read -p "Press ENTER when contacts are found..."

echo ""
echo "✅ STEP 5: Send First 5 Emails (Warm-up)"
echo "-------------------------------------------"
echo "Choose your top 5 targets (highest violation counts)"
echo ""
echo "Email templates in: email-setup-guide.md"
echo ""
echo "PERSONALIZE each email with:"
echo "  - Their company name (3+ times)"
echo "  - Specific violation count you found"
echo "  - Industry-specific regulation (CFPB, HIPAA, FDCPA)"
echo ""
echo "Example subject lines:"
echo "  - '[Company] Mobile App - 12 WCAG Violations Found'"
echo "  - '[Hospital] Patient Portal - ADA + HIPAA Risk'"
echo "  - '[Collector] Payment Portal - FDCPA Compliance Gap'"
echo ""
read -p "Press ENTER when first 5 emails are sent..."

echo ""
echo "✅ STEP 6: Set Up Daily Routine"
echo "-------------------------------------------"
echo "Create calendar reminders:"
echo ""
echo "MORNING (9-11 AM):"
echo "  - Send 5-10 personalized emails"
echo "  - Follow up on emails from 3 days ago"
echo ""
echo "AFTERNOON (2-4 PM):"
echo "  - Research 10 new companies"
echo "  - Scan and add to spreadsheet"
echo "  - Send 5-10 more emails"
echo ""
echo "EVENING (6-7 PM):"
echo "  - Check email responses"
echo "  - Update spreadsheet status"
echo "  - Prepare tomorrow's target list"
echo ""
read -p "Press ENTER to continue..."

echo ""
echo "✅ STEP 7: Week 1 Goals"
echo "-------------------------------------------"
echo "By end of Week 1:"
echo "  📊 100 companies scanned and in spreadsheet"
echo "  📧 50 personalized emails sent"
echo "  💬 2-3 responses expected"
echo "  📞 1-2 demo calls scheduled"
echo ""
echo "Warming schedule:"
echo "  - Day 1: 5 emails"
echo "  - Day 2: 7 emails"
echo "  - Day 3: 10 emails"
echo "  - Day 4-7: 10-15 emails/day"
echo ""

echo ""
echo "=========================================="
echo "  🚀 YOU'RE READY TO LAUNCH!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. ✅ Email created and configured"
echo "2. ✅ Spreadsheet ready"
echo "3. ✅ First 20 companies scanned"
echo "4. ✅ First 5 emails sent"
echo "5. 📈 Scale up to 10-15/day by Week 2"
echo ""
echo "Expected Month 1 Results:"
echo "  - 300 companies scanned"
echo "  - 300 emails sent"
echo "  - 9-15 responses (3-5% rate)"
echo "  - 5-7 demos scheduled"
echo "  - 2-3 deals closed"
echo "  - \$40K-\$120K in contracts"
echo ""
echo "Good luck! 🎯"
echo ""
